version: 2
updates:
  - package-ecosystem: "github-actions" # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker" # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    schedule:
      interval: "weekly"
